export const CATEGORIES = [
  "Electronics",
  "Fashion",
  "Beauty",
  "Home",
  "Toys",
  "Sport",
  "Books",
  "Motors",
  "Property",
  "Other",
];

export const SUBCATEGORIES = {
  Electronics: [
    "Phones & Accessories",
    "Gaming",
    "TV & Video",
    "Cameras & Photography",
    "Computers,PCs & Laptops",
    "Computer accessories",
    "Home Appliances",
    "Sound & Audio",
    "Tablets & eReaders",
    "Wearables",
    "Virtual Reality",
  ],
  "Fashion": ["Women", "Men", "Girls", "Boys", "Unisex"],
  Beauty: [
    "Fragrance",
    "Perfume for men",
    "Perfume for women",
    "Makeup",
    "Haircare",
    "Skincare",
    "Tools and Accessories",
    "Mens grooming",
    "Gift sets",
  ],
  "Home": [
    "Bedding",
    "Bath",
    "Home Decor",
    "Kitchen and Dining",
    "Home storage",
    "Furniture",
    "Garden & outdoor",
    "Lamps & Lighting",
    "Tools & Home improvement",
  ],
  Toys: [
    "Kids toys",
    "Baby transport",
    "Nursing and feeding",
    "Bathing & Baby care",
    "Baby clothing & shoes",
    "Parenting Books",
  ],
  "Sport": [
    "Camping & Hiking",
    "Cycling",
    "Scooters & accessories",
    "Strength & weights",
    "Yoga",
    "Cardio equipment",
    "Water sports",
    "Raquet sports",
    "Boxing",
    "Other",
  ],
  Books: [
    "Childrens books",
    "Fiction books",
    "Comics",
    "Sports",
    "Science",
    "Diet, Health & Fitness",
    "Business & Finance",
    "Biogpraphy & Autobiography",
    "Crime & Mystery",
    "History",
    "Cook Books & Food",
    "Education",
    "Foreign Language Study",
    "Travel",
    "Magazine",
    "Other",
  ],
  Motors: [
    "Used Cars",
    "Motorcycles & Scooters",
    "Heavy vehicles",
    "Boats",
    "Number plates",
    "Auto accessories",
    "Car Technology",
  ],
  Property: [
    "For Sale \nHouses & Apartment",
    "For Rent \nHouses & Apartment",
    "For Rent \nShops & Offices",
    "Guest Houses",
  ],
  Other: ["Office Supplies","Daily & Travel Items","Musical Instruments","Pet Supplies"],
};

export const SUBSUBCATEGORIES = {
  Women: [
    "Sneakers",
    "Flats",
    "Activewear & Sportswear",
    "Jewelry",
    "Dresses",
    "Tops",
    "Coats & Jackets",
    "Jumpers & Cardigans",
    "Bags",
    "Heels",
    "Sandals,slippers and flip-flops",
    "Boots",
    "Sports shoes",
    "Sunglasses",
    "Eye-wear",
    "Hair accessories",
    "Belts",
    "Watches",
    "Modest wear",
    "Jumpsuits & Playsuits",
    "Hoodies & Sweatshirts",
    "Jeans",
    "Suits & Blazers",
    "Swimwear & Beachwear",
    "Bottoms",
    "Skirts",
    "Other",
  ],
  Men: [
    "Shoes & Boots",
    "Activewear & Sportswear",
    "Polo Shirts & T- Shirts",
    "Shirts",
    "Sneakers",
    "Loafers & slip-ons",
    "Formal shoes",
    "Sports shoes",
    "Coats & Jackets",
    "Jumpers & Cardigans",
    "Bags & Wallet",
    "Trousers",
    "Hair accessories",
    "Belts",
    "Eyewear",
    "Sunglasses",
    "Nightwear & Loungewear",
    "Hoodies & Sweatshirts",
    "Jeans",
    "Suits & Blazers",
    "Swimwear & Beachwear",
    "Shorts",
    "Other",
  ],
  Girls: [
    "Bags",
    "Bottoms",
    "Dresses",
    "Tops and Tees",
    "Hats",
    "Accessories",
    "Jumpsuits",
    "Nightwear & Loungewear",
    "Socks",
    "Hoodies & Sweatshirts",
    "Swimwear & Beachwear",
  ],
  Boys: [
    "Hats",
    "Hoodies & Sweatshirts",
    "Nightwear & Loungewear",
    "Bottoms",
    "Shirts & T-Shirts",
    "Socks",
    "Tops",
  ],
  Unisex: [
    "Shoes & Boots",
    "Activewear & Sportswear",
    "Shirts",
    "T- Shirts & Vests",
    "Coats & Jackets",
    "Jumpers & Cardigans",
    "Bags & Accessories",
    "Trousers",
    "Chinos",
    "Jumpsuits & Playsuits",
    "Nightwear",
    "Loungewear",
    "Hoodies & Sweatshirts",
    "Jeans",
    "Suits & Blazers",
    "Swimwear & Beachwear",
    "Shorts",
    "Other",
  ],
};
